# This workflow will do a clean install of node dependencies, build the source code and run tests

name: 'Pre merge checks'

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  node-version: 16.x

jobs:
  dependencies:
    name: 'Install dependencies'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Cache node modules
        uses: actions/cache@v4
        id: restore-dependencies
        env:
          cache-name: cache-node-modules
        with:
          # Cache node_modules. To cache global, you may try ~/.npm
          path: ./node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm i

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [dependencies]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Load node modules
        uses: actions/cache@v4
        id: restore-dependencies
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
      - run: npm run lint

  no-datapass-staging:
    name: 'No link to staging.datapass'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - run: npm run check-no-datapass-staging

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [dependencies]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Load node modules
        uses: actions/cache@v4
        id: restore-dependencies
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
      - run: npm run build
      - uses: actions/cache@v4
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: [dependencies]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Load node modules
        uses: actions/cache@v4
        id: restore-dependencies
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
      - run: npm run test
